GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Arskan seikkailut",
    "author": "R.A. Mbo",
    "url": "ratatata.fi/arseikkailut",
    "userId": "61b642ef6fd9e041ec4feb73"
}

###

GET http://localhost:3001/api/users
Content-Type: application/json