GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer $2b$10$y5RHTsnJFTbCctUgefZYOeb.NDqV20JkK4zVe1SIyT/m2AjJUoElq

{
    "title": "Jaskan seikkailut",
    "author": "J.H. Hukkareissu",
    "url": "kuukkeli.com/hukkareissu",
    "userId": "61cca524c257b4e9910e03e8"
}

####

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Norppa",
    "name" : "Noora Kauhanen",
    "password" : "jo"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username" : "Jjokunen",
    "password" : "jokujannu"
}
