GET http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcnBwYSIsImlkIjoiNjFkMWM2NjczNzhkYzdmNTEyOTAzZDQ3IiwiaWF0IjoxNjQxNDA2NzQ3LCJleHAiOjE2NDE0MTAzNDd9.aaOpyFb0EWP6nE836nRakQDEgmbMU-Y2rVDlRxymS6A

###blog api calls

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVra2VsaSIsImlkIjoiNjFkMWU2ZDZjOTM0M2NjZGQ1M2U0MmU1IiwiaWF0IjoxNjQxMjMxMjAzLCJleHAiOjE2NDEyMzQ4MDN9.002ZjJouMKGAsuKNxk5sziBbbTL4ob7c0dX80C0y-RU

{
    "title": "Cthulhun seikkailut",
    "author": "J.H. Hukkareissu",
    "userId": "61d1deabb443feec57a9d1b6"
}

###

DELETE http://localhost:3003/api/blogs/61f50d86905828ea8c03ac72
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvbmRlIiwiaWQiOiI2MWY1MGM2ZjkwNTgyOGVhOGMwM2FjNjEiLCJpYXQiOjE2NDM0NTA3NDUsImV4cCI6MTY0MzQ1NDM0NX0.G294LT7ZS4Rc1i4DZ07AUcshChgMmh2tj-Kl6gHGKb4

####user calls 

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "jonde",
    "name" : "jonde sumusalo",
    "password" : "asd"
}

###Login calls

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username" : "Norppa",
    "password" : "jook"
}

###